plugins {
    id 'com.android.application'
}

android {
    namespace 'com.guidrthai.massage'
    compileSdk 36

    defaultConfig {
        applicationId 'com.guidrthai.massage'
        minSdk 23
        targetSdk 36
        versionCode 38
        versionName "38.0"
    }

    signingConfigs {
        release {
            storeFile file("../massage-upload-key.jks")
            storePassword "massage2026"
            keyAlias "massage-upload"
            keyPassword "massage2026"
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            versionNameSuffix "-debug"
        }
    }
}

